server.addr: 127.0.0.1:80
redis:
    server: 1.1.1.1:6791
    password: ""
    db: 0
token:
  # 单位为分钟
  expireTime: 110
cookie:
  domain: XXXXX
  path: XXXXX
ldap:
  server: XXXXXX
  port: 389
  baseDN: "OU=XXXXXX,OU=XXXXXX,OU=XXXXXX,DC=XXXXXX,DC=XXXXXX"
  username: "XXXXXX"
  password: "XXXXXX"
  domain: "XXXXXX"
log:
  path: /opt/logs/sso/
  name: sso.log
db:
  name: XXXXXX
  addr: IP:PORT
  username: XXXXXX
  password: XXXXXX